config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "auth/google/callback",    to: 'sessions#create'
  get 'auth/failure',            to: redirect('/')
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get 'logout',                  to: 'sessions#destroy'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'


  namespace :manager do
    resources :units, only: [:edit, :update, :index, :show]
    resources :users, only: [:index, :edit, :show, :update, :new, :create, :destroy]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :charges

  resource :dashboard, only: :show
  resources :events, only: :index do
    post 'attend', on: :member
    delete 'remove', on: :member
  end

  get "account/edit/:id", to: "users#edit", as: 'edit_user'
  resource :user, only: :update

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users
  has_many :users, :through => :event_users


  validates_presence_of :name, :details, :date


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:attend, :remove]
  def index
    @events = Event.all
  end


  def attend
    if @event.users.include?(current_user) == true
      flash[:alert] = "You've already RSVPed!"
      redirect_to events_path
    else @event.users << current_user
      flash[:success] = "You've saved a spot!"
      redirect_to events_path
    end
  end

  def remove
    @event.users.destroy(User.find(params[:user_id]))
    redirect_to manager_event_path(@event)
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/manager/events_controller.rb
class Manager::EventsController < ApplicationController
  before_action :set_event, only: [:show,:edit, :update, :destroy]

  def index
    @events = Event.all.order(:id)
  end

  def show

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "#{@event.name} has been scheduled!"
      redirect_to manager_events_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    @event.update(event_params)
    if @event.save
      flash[:success] = "#{@event.name} details have been modified!"
      redirect_to manager_event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:delete] = "Event has been removed from dashboard"
    redirect_to manager_events_path
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :details, :date)
    end


end

app/controllers/manager/units_controller.rb
class Manager::UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update]

  def index
    @units = Unit.all.order(:id)
  end

  def show

  end

  def edit

  end

  def update
    if @unit.update(unit_params)
      flash[:alert] = "You've updated #{@unit.unit_number}'s details!"
      redirect_to manager_units_path
    else
      render :edit
    end
  end


  private

    def set_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:rent, :rent_due, :rent_due_date)
    end
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]

  def index
    @users = User.where(role: "renter")
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:alert] = "You've created a new tenant!"
      redirect_to manager_users_path
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @user.update(user_params)
      flash[:success] = "You've updated #{@user.first_name}'s profile"
      redirect_to manager_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:alert] = "User is removed from the system."
    redirect_to manager_users_path
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :unit_id)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/views/manager/events/edit.html.erb
<%= form_for [:manager, @event] do |f| %>
<%= f.text_field :name, placeholder: "#{@event.name}" %>
<%= f.text_area  :details, placeholder: "#{@event.details}" %>
<%= f.date_select :date %>
<%= f.submit "Edit Event Details" %>
<% end %>

app/views/manager/events/index.html.erb
<div class="manager-event-index-header">
  Manage Property Events
</div>
<div class="manager-event-index-main">
  <table style="width:80%" class= "manager-event-index-table">
    <tr>
      <th> Event Page</th>
      <th>Event Details</th>
      <th>Event Date</th>
      <th></th>
      <th></th>
    </tr>
      <% @events.each do |event| %>
    <tr>
      <td><%= button_to event.name, manager_event_path(event), method: :get, class: 'show-event-button' %> </td>
      <td><%= event.details %> </td>
      <td><%= event.date %></td>
      <td><%= button_to "Change Details", edit_manager_event_path(event), method: :get, class: 'edit-event-button' %>  </td>
      <td><%= button_to "Delete Event", manager_event_path(event), method: :delete, class: 'delete-event-button' %> </td>
    </tr>
    <% end %>
  </table>
</div>
  <div class="edit-details">
  <%= button_to "Create New Resident Event!", new_manager_event_path, method: :get, class: "new-event-button"%>
  <%= button_to "Go Back To Dashboard", dashboard_path, method: :get, class: "go-back-button"%>
  </div>

app/views/manager/events/new.html.erb
<%= form_for [:manager, @event] do |f| %>
<%= f.text_field :name, placeholder: "Event Name" %>
<%= f.text_area  :details, placeholder: "Event Details" %>
<%= f.date_select :date %>
<%= f.submit "Create Event" %>
<% end %>

app/views/manager/events/show.html.erb
<div class="event-show">
  <%= render 'shared/event_show' %>
</div>