config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "auth/google/callback",    to: 'sessions#create'
  get 'auth/failure',            to: redirect('/')
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get 'logout',                  to: 'sessions#destroy'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'


  namespace :manager do
    resources :units, only: [:edit, :update, :index, :show]
    resources :users, only: [:index, :edit, :show, :update, :new, :create, :destroy]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :charges

  resource :dashboard, only: :show
  resources :events, only: :index do
    post 'attend', on: :member
    delete 'remove', on: :member
  end

  get "account/edit/:id", to: "users#edit", as: 'edit_user'
  resource :user, only: :update

end

app/views/shared/_dashboard.html.erb
<% if current_user && current_user.manager? %>
  <%= render 'shared/manager_dashboard' %>
<% else current_user %>
  <%= render 'shared/renter_dashboard' %>
<% end %>

app/views/shared/_event_show.html.erb
<% if @event.users.nil? %>
<div class="event-show">
  Name:<%= @event.name %>
  Details:<%= @event.details %>
  Date:<%= @event.date %>
</div>
<% else %>
  Name: <%= @event.name %><br>
  Details:  <%= @event.details %><br>
  Date: <%= @event.date %>
<table style="width:80%" class= "manager-event-show-table">
  <tr>
    <th>Resident Name</th>
    <th>Resident Unit</th>
    <th>Resident Email</th>
    <th></th>
  </tr>
  <% @event.users.each do |user| %>
  <tr>
    <th><%= user.first_name %> <%= user.last_name %></th>
    <th><%= user.unit.unit_number %></th>
    <th><%= user.email %></th>
    <th><%= button_to "Remove Attendee", remove_event_path(@event), method: :delete, params: {user_id: user.id}, class: "remove-attendee-button"%>  </th>
  </tr>
  <% end %>
</table>
<% end %>

<div class="edit-details">
  <%= button_to "Manager Events Dashboard", manager_events_path, method: :get, class: "go-back-button-show"%>
</div>

app/views/shared/_flash.html.erb
<div class="center-flash">
  <% flash.each do |name, msg| %>
  <div class="<%=name%>"><%=raw(msg)%></div>
  <% end %>
</div>

app/views/shared/_manager_dashboard.html.erb
<h1 id= "manager-dashboard-top"> Manager Dashboard </h1>
<div class="manager-dashboard-main">
  <%= button_to "View All Units", manager_units_path, method: :get , class: 'manager-dashboard-button' %>
  <%= button_to "View All Events", manager_events_path, method: :get, class: 'manager-dashboard-button' %>
  <%= button_to "View All Tenants", manager_users_path, method: :get, class: 'manager-dashboard-button' %>
  <%= button_to "Edit Details", edit_manager_user_path(current_user), method: :get, class: 'manager-dashboard-button' %>
</div>

app/views/shared/_manager_tenant_unit.html.erb
<tr>
<% @users.each do |user| %>
  <% if user.unit == nil %>
    <td><%= user.first_name %> <%= user.last_name %></td>
    <td><%= user.email %> </td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= button_to "Edit User Info", edit_manager_user_path(user), method: :get, class: "edit-unit-button" %>  </td>
    <td><%= button_to "Remove Tenant", manager_user_path(user), method: :delete, class: "delete-unit-button" %>  </td>
  <% else %>
    <td><%= user.first_name %> <%= user.last_name %></td>
    <td><%= user.email %> </td>
    <td><%= user.unit.unit_number %></td>
    <td><%= user.unit.rent_due_date %> </td>
    <td><%= user.unit.paid? %> </td>
    <td><%= button_to "Edit User Info", edit_manager_user_path(user), method: :get, class: "edit-unit-button" %>  </td>
    <td><%= button_to "Remove Tenant", manager_user_path(user), method: :delete, class: "delete-unit-button" %>  </td>
  <% end %>
</tr>
<% end %>

app/views/shared/_nav_login.html.erb
<% if current_user  %>
  <%= link_to "Logout", logout_path %>
<% end %>

app/views/shared/_no_unit.html.erb
<% if current_user.unit == nil %>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
<% else %>
  <td><%= current_user.unit.unit_number %> </td>
  <td><%= current_user.unit.unit_type %></td>
  <td><%= number_to_currency(current_user.unit.rent) %></td>
  <td><%= current_user.unit.unit_due_date %></td>
  <td><%= render 'shared/rent_paid'%></td>
<% end %>

app/views/shared/_rent_paid.html.erb
<% if current_user.unit.rent_due != 0 %>
 <%= link_to "Pay Rent", new_charge_path %>
<% else %>
   Paid
<% end %>

app/views/shared/_renter_dashboard.html.erb
<div class="renter-dashboard-main">
  <div class="renter-dashboard-head">
    <p> Account Management </p>
  </div>
  <table style="width:80%" class= "renter-table">
    <tr>
      <th>Unit Occupant</th>
      <th>Unit Number</th>
      <th>Unit Type</th>
      <th>Rent</th>
      <th>Rent Due Date</th>
      <th>Rent Status</th>
    </tr>
    <tr>
      <td><%= current_user.first_name %> <%= current_user.last_name %> </td>
      <%= render 'shared/no_unit' %>
    </tr>
  </table>
  <div class= "edit-details">
    <p><%= link_to "Edit Account Details", edit_user_path(current_user) %></p>
    <p><%= link_to "View Available Events", events_path %></p>
 </div>