config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "auth/google/callback",    to: 'sessions#create'
  get 'auth/failure',            to: redirect('/')
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get 'logout',                  to: 'sessions#destroy'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'


  namespace :manager do
    resources :units, only: [:edit, :update, :index, :show]
    resources :users, only: [:index, :edit, :show, :update, :new, :create, :destroy]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :charges

  resource :dashboard, only: :show
  resources :events, only: :index do
    post 'attend', on: :member
    delete 'remove', on: :member
  end

  get "account/edit/:id", to: "users#edit", as: 'edit_user'
  resource :user, only: :update

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end 

end

app/views/welcome/index.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h1> Resident Portal </h1>
  </div>
</div>
<div class = "welcome-content">
  <p class= "welcome">With our convenient Resident Portal, we've made it easy and convenient for you to pay your rent and submit service requests online.</p>
  <p class = "welcome">Log in, tell us what you need, and we'll get it done!</p>

  <div id="welcome-access-account">
    <% if current_user.nil?%>
    <div class="account-button">
      <%= button_to "Sign in with Google", "/auth/google", method: :get, class: 'sign-in' %>
      <%= button_to "Don't have Google? Log In Here", login_path, method: :get, class: 'sign-in-no-google'%>
    </div>
    <% else %>
    <div >
      <%= button_to "Access Account", dashboard_path, method: :get, class: 'account-button-access' %>
    </div>
    <% end %>
  </div>
</div>