config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "auth/google/callback",    to: 'sessions#create'
  get 'auth/failure',            to: redirect('/')
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get 'logout',                  to: 'sessions#destroy'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'


  namespace :manager do
    resources :units, only: [:edit, :update, :index, :show]
    resources :users, only: [:index, :edit, :show, :update, :new, :create, :destroy]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :charges

  resource :dashboard, only: :show
  resources :events, only: :index do
    post 'attend', on: :member
    delete 'remove', on: :member
  end

  get "account/edit/:id", to: "users#edit", as: 'edit_user'
  resource :user, only: :update

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new

  end

  def create
    @amount = (current_user.unit.rent_due * 100).round
    Stripe.api_key = ENV["stripe_secret"]
    customer = StripeService.initiate_customer(params[:stripeEmail], params[:stripeToken])
    begin
      StripeService.initiate_charge(customer, @amount, current_user.unit.unit_number)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
      current_user.unit.update(rent_due: 0)
  end


end

app/views/charges/create.html.erb
<div class="rent-paid">
  <h2>Thanks! You've successfully paid your monthly rent for Unit:<%= current_user.unit.unit_number %>! Your monthly balance is <%= current_user.unit.rent_due %>  <strong> </h2>
</div>
<div class="edit-details">
  <%= link_to "Go Back to Dashboard", dashboard_path %>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Rent Due: <%= number_to_currency(current_user.unit.rent) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"
          data-key="<%= ENV["stripe_key"] %>"
          data-description="Rent Due"
          data-amount= "<%= (current_user.unit.rent_due * 100) %> "
          data-email="<%= current_user.email %>"
          data-locale="auto">
  </script>
<% end %>